Fix CTE Report For Arrow Function Missing Return
Issue: https://gitcode.com/openharmony/arkcompiler_ets_frontend/issues/8755
Reason
TypeError: no return value

Description
Fix TypeError

Signed-off-by: likaizheng <likaizheng@huawei.com>